# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=200),
        ),
    ]
