# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='product_id',
        ),
    ]
